services:
  - type: web
    name: myntmore-video-transcriber
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py"
    healthCheckPath: "/_stcore/health"
    autoDeploy: true 